server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 888888
    url: jdbc:mysql://localhost:3306/activity?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true

mybatis:
   mapperLocations: classpath:/mapper/*.xml